spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
departamentos.service.url=${DEPARTAMENTOS_SERVICE_URL:http://departamentos-service:8081}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# RABBITMQ
spring.rabbitmq.host=${RABBITMQ_HOST:message-broker}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASS:admin}

# RETRY CONFIG
resilience4j.retry.instances.departamentoRetry.max-attempts=3
resilience4j.retry.instances.departamentoRetry.wait-duration=2s
resilience4j.retry.instances.departamentoRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException

# CIRCUIT BREAKER CONFIG
resilience4j.circuitbreaker.instances.departamentoCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.departamentoCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.departamentoCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.departamentoCB.wait-duration-in-open-state=10s
