pipeline {
    agent any

    environment {
        SERVICE_NAME = 'notificaciones-service'
        IMAGE_TAG    = "${env.BUILD_NUMBER}"
        SONAR_TOKEN  = credentials('sonar-token')
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Código obtenido para: ${SERVICE_NAME}"
            }
        }

        stage('Build') {
            steps {
                dir('notificaciones') {
                    sh 'mvn clean compile -DskipTests -q'
                    echo 'Compilación exitosa'
                }
            }
        }

        stage('Test') {
            steps {
                dir('notificaciones') {
                    sh 'mvn verify -q'
                    echo 'Tests y cobertura generados'
                }
            }
            post {
                always {
                    dir('notificaciones') {
                        junit allowEmptyResults: true,
                              testResults: 'target/surefire-reports/*.xml'
                    }
                }
            }
        }

        stage('SonarQube') {
            steps {
                dir('notificaciones') {
                    withSonarQubeEnv('SonarQube') {
                        sh """
                            mvn sonar:sonar \
                                -Dsonar.projectKey=notificaciones-service \
                                -Dsonar.projectName='Notificaciones Service' \
                                -Dsonar.token=${SONAR_TOKEN} \
                                -q
                        """
                    }
                }
                echo 'Análisis enviado a SonarQube'
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
                echo 'Quality Gate aprobado'
            }
        }

        stage('Package') {
            steps {
                dir('notificaciones') {
                    sh "docker build -t ${SERVICE_NAME}:${IMAGE_TAG} -t ${SERVICE_NAME}:latest ."
                    echo "Imagen construida: ${SERVICE_NAME}:${IMAGE_TAG}"
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline de ${SERVICE_NAME} completado — Build #${env.BUILD_NUMBER}"
        }
        failure {
            echo "Pipeline de ${SERVICE_NAME} FALLIDO — Build #${env.BUILD_NUMBER}"
        }
        always {
            cleanWs()
        }
    }
}