server:
  port: 8085

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Auth service — público, sin filtro JWT
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # Empleados
        - id: empleados-service
          uri: lb://empleados-service
          predicates:
            - Path=/empleados/**
          filters:
            - name: JwtAuthFilter

        # Departamentos
        - id: departamentos-service
          uri: lb://departamentos-service
          predicates:
            - Path=/departamentos/**
          filters:
            - name: JwtAuthFilter

        # Perfiles
        - id: perfiles-service
          uri: lb://perfiles-service
          predicates:
            - Path=/perfiles/**
          filters:
            - name: JwtAuthFilter

        # Notificaciones
        - id: notificaciones-service
          uri: lb://notificaciones-service
          predicates:
            - Path=/notificaciones/**
          filters:
            - name: JwtAuthFilter

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
