spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8082

# RABBITMQ
spring.rabbitmq.host=${RABBITMQ_HOST:message-broker}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASS:admin}
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
jwt.recovery-expiration-ms=${JWT_RECOVERY_EXPIRATION_MS:3600000}

# RESILIENCE4J CONFIG
resilience4j.retry.instances.authRetry.max-attempts=3
resilience4j.retry.instances.authRetry.wait-duration=2s
resilience4j.retry.instances.authRetry.retry-exceptions=org.springframework.web.client.ResourceAccessException,java.io.IOException

resilience4j.circuitbreaker.instances.authCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.authCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.authCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.authCB.wait-duration-in-open-state=10s

# EUREKA CONFIG
eureka.client.service-url.default-zone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
